server:
  port:
    9001
auth:
  update: ${auth.update}
  path: ${AUTHPATH}

spring:
  data:
    redis:
      host: ${host}
      port: ${port}
  main:
    web-application-type:
      reactive
  cloud:
    gateway:
      routes:
        - id: user_auth
          uri: http://localhost:8083/
          predicates:
            - Path=/auth/**
          filters:
            - AuthBackendFilter
        - id: patient_info
          uri: http://localhost:8081/
          predicates:
            - Path=/patient/**
          filters:
            - VerifyTokenFilter
            - AuthBackendFilter
        - id: patient_note
          uri: http://localhost:8082/
          predicates:
            - Path=/notes/**
          filters:
            - VerifyTokenFilter
            - AuthBackendFilter
        - id: patient_risque
          uri: http://localhost:8084
          predicates:
            - Path=/risques/**
          filters:
            - VerifyTokenFilter
            - AuthBackendFilter
        - id: front
          uri: http://localhost:4200/
          predicates:
            - Path=/**, /login/**, /gestion/**
